In [16]:
import numpy as np
import scipy.optimize as so


In [20]:
E = np.array([-222.242813, -222.110401, -222.173452]) - (-222.087245)
natoms = 4
E = E/natoms
E

array([-0.038892  , -0.005789  , -0.02155175])

In [21]:
S = np.array([[8.0,6.0,1.0],[-8.0,6.0,1.0],[0.0,-2.0,1.0]])
S

array([[ 8.,  6.,  1.],
       [-8.,  6.,  1.],
       [ 0., -2.,  1.]])

In [22]:
np.linalg.lstsq(S, E, rcond=None)

(array([-2.06893750e-03, -9.85937500e-05, -2.17489375e-02]),
 array([], dtype=float64),
 3,
 array([11.3137085 ,  8.7946051 ,  1.28643735]))